version: "3.5"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - affordibit

networks:
  affordibit:
    driver: bridge
