#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build
if [ $? -ne 0 ]; then
  echo "Build failed, aborting push."
  exit 1
fi

yarn test
if [ $? -ne 0 ]; then
  echo "Tests failed, aborting push."
  exit 1
fi

yarn e2e:test
if [ $? -ne 0 ]; then
  echo "End-to-end tests failed, aborting push."
  exit 1
fi
